name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 1 * * *' # every night at 1 am UTC
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: windows-2019
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 30days # Set this to 0 to delete all artifacts
